update dependencies, now at version 1.2.4
- upgrade most dependencies, but not CoffeeScript, since the latest
  version generates code that can't be run in older versions of node

- change to call `yaml.load()` instead of `yaml.safeLoad()` since it's no
  longer supported, noticed via an error message:

  ```
  Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
  ```